version: "3.4"
services:
  database:
    container_name: database
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "calimero"
      MYSQL_DATABASE: "cours_tp"
      MYSQL_USER: "younes"
      MYSQL_PASSWORD: "younes"
    ports:
      - 3306:3306
    volumes:
      - /home/calimero/prog/java/mysql/data/dbdata:/var/lib/mysql
  
  phpmyadmin:
    container_name: phpma
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: "calimero"
      PMA_HOST: "database"
    depends_on:
      - database
    ports:
      - 8081:80
